version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: mongoPass
    ports: 
      - 27017:27017